### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by anupam-git** [subins2000/p2pt#2]
Hey.
This library seems cool and could have millions of usages.

It needs a good documentation even if it is self explanatory. Let me know if you are interested in a documentation. I can send a PR :)

**Comment by subins2000** [comment]
Hi !
Thank you ! I've just elaborated more in the README. But, there should be an API docs, yeah that'd be good.

I'm in the process of making some cool apps with P2PT. That way, I know what all need to be added extra to make P2PT better to be used as a library. Hence, I haven't put much effort to the docs. There maybe some breaking changes in the future.

What do you think about the new README ?

**Comment by anupam-git** [comment]
The README looks better now. :)
Still I prefer API Docs while implementing a library.

Versioning this library as a pre-release with v0.X.X and a pre-release API Docs would still be usefull.

I'll send a PR tomorrow with a basic doc. See if you like it.

**Comment by anupam-git** [comment]
BTW, I made some P5.js games about 5-6 yrs ago. Dont know if I still have them. Would be fun to have multiplayer functionality..

I'll let you know if I find those.. :D

**Comment by subins2000** [comment]
Yeah, API docs would be better. I'm making [this game](https://vett.space) now. After I publish it (soon, hopefully tomorrow), will definitely publish a basic API docs of P2PT.

Oh yeah, having a multiplayer feature would be cool ! What games have you made ?
