### ISSUE TITLE
How to send files?

### ISSUE THREAD

**Issue by slavkojos** [subins2000/p2pt#35]
How do you send files with this? do you just wait in the "msg" event for file transfer complete, or do you have to assemble the chunks?
I also tried using it with simple-peer-files, but no luck.
Sorry I am still new with WebRTC and simple peer, I would really appreciate if someone can explain the process a bit better

**Comment by draeder** [comment]
I haven't tried it, but you should be able to load and send the file as a message, then wait for it on the other side and read it as a file. Per the [readme](https://github.com/subins2000/p2pt/blob/master/README.md) long messages are sent as chunks, so it should ready for files.

**Comment by subins2000** [comment]
You don't have to assemble the chunks, it will be done by the library itself.
