### ISSUE TITLE
Add browser build and/or esmodule support

### ISSUE THREAD

**Issue by therealadityashankar** [subins2000/p2pt#8]
I see people using this in their browser

**Comment by subins2000** [comment]
Can you please elaborate ?

**Comment by therealadityashankar** [comment]
@subins2000 I basically think that people might want to add this as a `<script>` tag on their websites, rather than using browserify while creating their websites, so it'd be great if you could use some bundler to give a bundled version of p2pt / give an esmodule build instead, that can be directly used via jsdelivr (I prefer this if possible)

**Comment by subins2000** [comment]
Ah yeah true. The [simple example](https://codepen.io/subins2000/pen/MWKwRYJ) mentioned in README uses the service of wzrd.in for getting a bundled p2pt : https://wzrd.in/standalone/p2pt@1.2.0

But yeah it'd be better if there was a standalone script loadable with `<script>` and is fast. PRs appreciated. Perhaps a script to make a `dist` folder and `p2pt.js` in it and added to package.json to easily call

**Comment by therealadityashankar** [comment]
I didn't know wzrd.in existed, you should probably just use that if its stable enough, I know I would

**Comment by therealadityashankar** [comment]
its not stable enough, consider building instead
